#!/bin/bash

# Check if the correct number of parameters is provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Disable strict host key checking for this session
export SSH_OPTS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp $SSH_OPTS -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check the exit status of scp
if [ $? -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi

